# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"
servers:
  - url: "/api" # By providing "/api" as the value of url, you’ll be able to access all of your API paths relative to http://localhost:8000/api.
paths:
  /people: #The relative URL of your API endpoint
    get: #The HTTP method that this URL endpoint will respond to
      operationId: "people.read_all" #The Python function that’ll respond to the request
      tags: #The tags assigned to this endpoint, which allow you to group the operations in the UI
        - "People"
      summary: "Read the list of people"  #The UI display text for this endpoint
      responses:  #The status codes that the endpoint responds with
        200:
          description:  "Successfully read people list"

components: {
  schemas:
    Person:
      type: "obejct"
      required:
        -lname
        properties:
        fname:
          type: "string"
        lname:
          type: "string"
}
  
